{
 "title": "Kubernetes Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1s",
 "panels": [
  { "title": "Kubernetes Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "App pods running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"techchallenge\", phase=\"Running\", pod=~\"tech-challenge-app-.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage - Application",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace='techchallenge', pod=~'tech-challenge-app.*'}[2m])) by (pod) / sum(kube_pod_container_resource_requests{pod=~\"tech-challenge-app.*\", resource=\"cpu\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Memory Usage - Application",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace='techchallenge', pod=~'tech-challenge-app.*'}) by (pod)"
    }
   ]
  },
  {
   "title": "Avg pod CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace='techchallenge', pod=~'tech-challenge-app.*'}[2m])) / sum(kube_pod_container_resource_requests{pod=~\"tech-challenge-app.*\", resource=\"cpu\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB pods running",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{namespace=\"techchallenge\", phase=\"Running\", pod=~\"tech-challenge-db-.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage - Database",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace='techchallenge', pod=~'tech-challenge-db.*'}[5m])) by (pod)"
    }
   ]
  },
  {
   "title": "Memory Usage - Database",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace='techchallenge', pod=~'tech-challenge-db.*'}) by (pod)"
    }
   ]
  },
  { "title": "NGINX Ingress Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Ingress Request Volume",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{controller_pod=~\"nginx-ingress-ingress-nginx-controller.*\", controller_class=\"k8s.io/ingress-nginx\", controller_namespace=\"ingress-nginx\"}[2m])) by (ingress), 0.001)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_nginx_process_resident_memory_bytes{controller_pod=~\"nginx-ingress-ingress-nginx-controller.*\", controller_class=\"k8s.io/ingress-nginx\", controller_namespace=\"ingress-nginx\"}) ",
     "legendFormat": "nginx"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_nginx_process_cpu_seconds_total{controller_pod=~\"nginx-ingress-ingress-nginx-controller.*\", controller_class=\"k8s.io/ingress-nginx\", controller_namespace=\"ingress-nginx\"}[2m])) ",
     "legendFormat": "nginx"
    }
   ]
  },
  { "title": "Application Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Requests per second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri!~\"(.*actuator.*|.*swagger-ui.*|.*api-docs.*)\"}[15s])) by (uri)"
    }
   ]
  },
  {
   "title": "Total of Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{uri!~\"(.*actuator.*|.*swagger-ui.*|.*api-docs.*)\"}[5m])) by (uri)"
    }
   ]
  }
 ]
}