name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  # Job para verificação de build e testes unitários em pull requests
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21' # Configuração para Java 21

      - name: Build and run tests
        run: |
          mvn clean install  # Comando para build e testes com Maven
